# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)	+=  focaltech_sec_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)	+=  focaltech_sec_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)	+=  focaltech_sec_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)	+=  focaltech_sec_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)	+=  focaltech_sec_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)   +=  focaltech_sec_point_report_check.o

obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)   +=  focaltech_sec_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)	+=  focaltech_sec_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SEC)   +=  focaltech_sec_flash/
